spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practicas
    username: admin
    password: admin
  jpa:
    show-sql: true

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
    ddl-auto: update